import { test } from 'node:test';
import assert from 'node:assert/strict';

import { CANARY } from '../src/canary.js';
import { VERSION } from '../src/model.js';
import { expand, pack } from '../src/codec.js';
import { encode36 } from '../src/base36.js';

// The wire format is not just the code: it is the code plus the tables in
// src/prior.js and src/dict.js. Change a table and every payload ever made
// means something else -- silently, because a range coder has no checksum to
// fail. These two tests are the tripwire.

test('the canary payload still decodes to the URL it was made from', () => {
  assert.equal(
    expand(CANARY.payload),
    CANARY.url,
    'The tables changed. Bump VERSION in src/model.js, then run `npm run train`.',
  );
});

test('the canary was generated by this version of the format', () => {
  assert.equal(
    CANARY.version,
    VERSION,
    'VERSION moved without regenerating the canary: run `npm run train`.',
  );
});

test('and the canary is what this build actually produces', () => {
  assert.equal(encode36(pack(CANARY.url).bytes), CANARY.payload);
});
